### ISSUE TITLE
Tests missing?

### ISSUE THREAD

**Issue by timwis** [cmuphillycapstone/ckanext-dictionary#4]
The documentation explains how to run tests, but it looks like the tests weren't included? Unless [this](https://github.com/cmuphillycapstone/CKAN_Data_Dictionary/blob/master/ckanext/dictionary/tests/test_plugin.py) is the only test?

**Comment by mcleinman** [comment]
Tests weren't included, but that was default text that was included in the readme.  I've removed it.
