### ISSUE TITLE
Add to CKAN extension registry

### ISSUE THREAD

**Issue by timwis** [cmuphillycapstone/ckanext-dictionary#5]
It would be great to [add this to the registry](http://extensions.ckan.org/add/)

**Comment by mcleinman** [comment]
Just submitted.  Will close this out when it's added.
Also up here (automatic when push it for the pip install): https://pypi.python.org/pypi/ckanext-dictionary

**Comment by jqnatividad** [comment]
Sorry guys about the delay... holidays & all.  This is a great addition!  Will put it to use ourselves.

**Comment by jqnatividad** [comment]
Added. https://github.com/ckan/extensions.ckan.org/issues/81

**Comment by mcleinman** [comment]
Thanks!
