### ISSUE TITLE
Add intro text, screenshots

### ISSUE THREAD

**Issue by timwis** [cmuphillycapstone/ckanext-dictionary#6]
Was just thinking of showing this to a few folks but realized they'd have to install CKAN and this extension to see what it does. Perhaps a screenshot or two in the readme would be helpful for viewers?

EDIT: Also, an introductory paragraph explaining what the extension is/does

**Comment by mcleinman** [comment]
Added intro.  Adding screenshots later today or tomorrow.

**Comment by timwis** [comment]
Looks great!
